version: "3.9"

services:
  database_CRUD:
    image: postgres
    container_name: database_crud
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=usercrud
    volumes:
      - pgdata:/data/postgres
  
  app:
    build: .
    container_name: usercrud
    restart: always
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local